version: '3.8'

services:
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "3000:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - enrollment-service
      - student-data-service
      - subjects-service
    networks:
      - microservices-network

  enrollment-service:
    build:
      context: ./services/enrollment-service
      dockerfile: Dockerfile
    container_name: enrollment-service
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network

  student-data-service:
    build:
      context: ./services/student-data-service
      dockerfile: Dockerfile
    container_name: student-data-service
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network

  subjects-service:
    build:
      context: ./services/subjects-service
      dockerfile: Dockerfile
    container_name: subjects-service
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
